### ISSUE TITLE
有一个地方写错了

### ISSUE THREAD

**Issue by Long17369** [LZWcc/educoder#1]
你这里的[链接](https://github.com/LZWcc/educoder/blob/main/04_C&CPP_input/03_birthday.cpp)年月日的位置错了

**Comment by LZWcc** [comment]
直接从vs上复制过来了 头歌上小改
已更新

**Comment by Long17369** [comment]
> 直接从vs上复制过来了 头歌上小改
> 已更新

记得关闭议题啊
